# Generated by Django 5.1.4 on 2025-04-08 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneroLivro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome_genero", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LivroTitulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("dt_publicacao", models.DateField()),
                ("sinopse", models.TextField()),
                ("capaPath", models.CharField(blank=True, max_length=100, null=True)),
                ("avaliacao", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LivroFavorito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nextbook_app.livrotitulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id_livro", models.AutoField(primary_key=True, serialize=False)),
                ("autor", models.CharField(max_length=100)),
                ("editora", models.CharField(blank=True, max_length=100)),
                ("num_paginas", models.IntegerField()),
                (
                    "titulo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextbook_app.livrotitulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PossuiGeneroLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="nextbook_app.generolivro",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="nextbook_app.livrotitulo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrefereGeneroLivro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="nextbook_app.generolivro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
