# Generated by Django 4.2 on 2025-04-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook_app', '0002_remove_livro_autor_remove_livro_contagem_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='data_criacao',
            new_name='criado_em',
        ),
    ]
