# Generated by Django 4.2 on 2025-04-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextbook_app', '0003_alter_favorito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='publicado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
